apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynginx
spec:
  replicas: 1
  selector:
    matchLabels:
      run: mynginx
  template:
    metadata:
      labels:
        run: mynginx
    spec:
      containers:
      - name: mynginx
        image: dlwnstj21/mynginx:latest
        ports:
        - containerPort: 80
        imagePullPolicy: Always

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      run: myapp
  template:
    metadata:
      labels:
        run: myapp
    spec:
      containers:
      - name: myapp
        image: dlwnstj21/demo-app:latest
        ports:
        - containerPort: 8080
        imagePullPolicy: Always

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydb
spec:
  replicas: 1
  selector:
    matchLabels:
      run: mydb
  template:
    metadata:
      labels:
        run: mydb
    spec:
      containers:
      - name: mydb
        image: dlwnstj21/mydb:latest
        ports:
        - containerPort: 3306
        imagePullPolicy: Always
