apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynginx
spec:
  replicas: 3
  selector:
    matchLabels:
      run: mynginx
  template:
    metadata:
      labels:
        run: mynginx
    spec:
      containers:
      - name: mynginx
        image: dlwnstj21/mynginx:latest
        ports:
        - containerPort: 80
        imagePullPolicy: Always
